---

- name: install dependencies for phantomjs
  apt: pkg={{item}}
  with_items:
    - git
    - build-essential 
    - g++ 
    - flex 
    - bison 
    - gperf 
    - ruby
    - perl
    - libsqlite3-dev 
    - libfontconfig1-dev 
    - libicu-dev 
    - libfreetype6 
    - libssl-dev
    - libpng-dev 
    - libjpeg-dev 
    - python 
    - libx11-dev 
    - libxext-dev
  tags:
  - phantomjs

- git: repo=git://github.com/ariya/phantomjs.git dest=/usr/local/src/phantomjs version=2.0 force=true
  tags:
  - phantomjs

- shell: ./build.sh --confirm --jobs 1 executable=/bin/bash chdir=/usr/local/src/phantomjs
  tags: 
  - phantomjs
