---
- name: start nginx
  service: name=nginx state=started enabled=yes

- name: stop nginx
  service: name=nginx state=stopped enabled=yes

- name: disable nginx
  service: name=nginx state=stopped enabled=no

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: wait for {{nginx__service}} port
  wait_for: port={{nginx__port}} delay=10
